
CREATE SCHEMA IF NOT EXISTS ex01;


CREATE TABLE IF NOT EXISTS ex01.users (
    id SERIAL PRIMARY KEY,
    username VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL
);
CREATE TABLE IF NOT EXISTS ex01.message (
    id SERIAL PRIMARY KEY,
    message TEXT NOT NULL,
    time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);